// Code generated by go-swagger; DO NOT EDIT.

package statistics_and_information

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/borud/wigle/models"
)

// CountriesReader is a Reader for the Countries structure.
type CountriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CountriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCountriesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewCountriesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCountriesOK creates a CountriesOK with default headers values
func NewCountriesOK() *CountriesOK {
	return &CountriesOK{}
}

/*
CountriesOK describes a response with status code 200, with default header values.

Request succeeded
*/
type CountriesOK struct {
	Payload *models.CountriesResponse
}

// IsSuccess returns true when this countries o k response has a 2xx status code
func (o *CountriesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this countries o k response has a 3xx status code
func (o *CountriesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this countries o k response has a 4xx status code
func (o *CountriesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this countries o k response has a 5xx status code
func (o *CountriesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this countries o k response a status code equal to that given
func (o *CountriesOK) IsCode(code int) bool {
	return code == 200
}

func (o *CountriesOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/stats/countries][%d] countriesOK  %+v", 200, o.Payload)
}

func (o *CountriesOK) String() string {
	return fmt.Sprintf("[GET /api/v2/stats/countries][%d] countriesOK  %+v", 200, o.Payload)
}

func (o *CountriesOK) GetPayload() *models.CountriesResponse {
	return o.Payload
}

func (o *CountriesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CountriesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCountriesInternalServerError creates a CountriesInternalServerError with default headers values
func NewCountriesInternalServerError() *CountriesInternalServerError {
	return &CountriesInternalServerError{}
}

/*
CountriesInternalServerError describes a response with status code 500, with default header values.

Unable to complete request
*/
type CountriesInternalServerError struct {
}

// IsSuccess returns true when this countries internal server error response has a 2xx status code
func (o *CountriesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this countries internal server error response has a 3xx status code
func (o *CountriesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this countries internal server error response has a 4xx status code
func (o *CountriesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this countries internal server error response has a 5xx status code
func (o *CountriesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this countries internal server error response a status code equal to that given
func (o *CountriesInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *CountriesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v2/stats/countries][%d] countriesInternalServerError ", 500)
}

func (o *CountriesInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/v2/stats/countries][%d] countriesInternalServerError ", 500)
}

func (o *CountriesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
