// Code generated by go-swagger; DO NOT EDIT.

package statistics_and_information

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GeneralStatsReader is a Reader for the GeneralStats structure.
type GeneralStatsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GeneralStatsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewGeneralStatsDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewGeneralStatsDefault creates a GeneralStatsDefault with default headers values
func NewGeneralStatsDefault(code int) *GeneralStatsDefault {
	return &GeneralStatsDefault{
		_statusCode: code,
	}
}

/*
GeneralStatsDefault describes a response with status code -1, with default header values.

successful operation
*/
type GeneralStatsDefault struct {
	_statusCode int
}

// Code gets the status code for the general stats default response
func (o *GeneralStatsDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this general stats default response has a 2xx status code
func (o *GeneralStatsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this general stats default response has a 3xx status code
func (o *GeneralStatsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this general stats default response has a 4xx status code
func (o *GeneralStatsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this general stats default response has a 5xx status code
func (o *GeneralStatsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this general stats default response a status code equal to that given
func (o *GeneralStatsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *GeneralStatsDefault) Error() string {
	return fmt.Sprintf("[GET /api/v2/stats/general][%d] generalStats default ", o._statusCode)
}

func (o *GeneralStatsDefault) String() string {
	return fmt.Sprintf("[GET /api/v2/stats/general][%d] generalStats default ", o._statusCode)
}

func (o *GeneralStatsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
