// Code generated by go-swagger; DO NOT EDIT.

package statistics_and_information

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// StatsReader is a Reader for the Stats structure.
type StatsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StatsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewStatsDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewStatsDefault creates a StatsDefault with default headers values
func NewStatsDefault(code int) *StatsDefault {
	return &StatsDefault{
		_statusCode: code,
	}
}

/*
StatsDefault describes a response with status code -1, with default header values.

successful operation
*/
type StatsDefault struct {
	_statusCode int
}

// Code gets the status code for the stats default response
func (o *StatsDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this stats default response has a 2xx status code
func (o *StatsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this stats default response has a 3xx status code
func (o *StatsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this stats default response has a 4xx status code
func (o *StatsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this stats default response has a 5xx status code
func (o *StatsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this stats default response a status code equal to that given
func (o *StatsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *StatsDefault) Error() string {
	return fmt.Sprintf("[GET /api/v2/stats/standings][%d] stats default ", o._statusCode)
}

func (o *StatsDefault) String() string {
	return fmt.Sprintf("[GET /api/v2/stats/standings][%d] stats default ", o._statusCode)
}

func (o *StatsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
