// Code generated by go-swagger; DO NOT EDIT.

package statistics_and_information

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUserStatisticsParams creates a new UserStatisticsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUserStatisticsParams() *UserStatisticsParams {
	return &UserStatisticsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUserStatisticsParamsWithTimeout creates a new UserStatisticsParams object
// with the ability to set a timeout on a request.
func NewUserStatisticsParamsWithTimeout(timeout time.Duration) *UserStatisticsParams {
	return &UserStatisticsParams{
		timeout: timeout,
	}
}

// NewUserStatisticsParamsWithContext creates a new UserStatisticsParams object
// with the ability to set a context for a request.
func NewUserStatisticsParamsWithContext(ctx context.Context) *UserStatisticsParams {
	return &UserStatisticsParams{
		Context: ctx,
	}
}

// NewUserStatisticsParamsWithHTTPClient creates a new UserStatisticsParams object
// with the ability to set a custom HTTPClient for a request.
func NewUserStatisticsParamsWithHTTPClient(client *http.Client) *UserStatisticsParams {
	return &UserStatisticsParams{
		HTTPClient: client,
	}
}

/*
UserStatisticsParams contains all the parameters to send to the API endpoint

	for the user statistics operation.

	Typically these are written to a http.Request.
*/
type UserStatisticsParams struct {

	/* User.

	   the name of the user for whom to get stats
	*/
	User *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the user statistics params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UserStatisticsParams) WithDefaults() *UserStatisticsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the user statistics params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UserStatisticsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the user statistics params
func (o *UserStatisticsParams) WithTimeout(timeout time.Duration) *UserStatisticsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the user statistics params
func (o *UserStatisticsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the user statistics params
func (o *UserStatisticsParams) WithContext(ctx context.Context) *UserStatisticsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the user statistics params
func (o *UserStatisticsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the user statistics params
func (o *UserStatisticsParams) WithHTTPClient(client *http.Client) *UserStatisticsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the user statistics params
func (o *UserStatisticsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUser adds the user to the user statistics params
func (o *UserStatisticsParams) WithUser(user *string) *UserStatisticsParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the user statistics params
func (o *UserStatisticsParams) SetUser(user *string) {
	o.User = user
}

// WriteToRequest writes these params to a swagger request
func (o *UserStatisticsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.User != nil {

		// query param user
		var qrUser string

		if o.User != nil {
			qrUser = *o.User
		}
		qUser := qrUser
		if qUser != "" {

			if err := r.SetQueryParam("user", qUser); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
