// Code generated by go-swagger; DO NOT EDIT.

package network_observation_file_upload_and_status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetKmlForTransIDParams creates a new GetKmlForTransIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetKmlForTransIDParams() *GetKmlForTransIDParams {
	return &GetKmlForTransIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetKmlForTransIDParamsWithTimeout creates a new GetKmlForTransIDParams object
// with the ability to set a timeout on a request.
func NewGetKmlForTransIDParamsWithTimeout(timeout time.Duration) *GetKmlForTransIDParams {
	return &GetKmlForTransIDParams{
		timeout: timeout,
	}
}

// NewGetKmlForTransIDParamsWithContext creates a new GetKmlForTransIDParams object
// with the ability to set a context for a request.
func NewGetKmlForTransIDParamsWithContext(ctx context.Context) *GetKmlForTransIDParams {
	return &GetKmlForTransIDParams{
		Context: ctx,
	}
}

// NewGetKmlForTransIDParamsWithHTTPClient creates a new GetKmlForTransIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetKmlForTransIDParamsWithHTTPClient(client *http.Client) *GetKmlForTransIDParams {
	return &GetKmlForTransIDParams{
		HTTPClient: client,
	}
}

/*
GetKmlForTransIDParams contains all the parameters to send to the API endpoint

	for the get kml for trans Id operation.

	Typically these are written to a http.Request.
*/
type GetKmlForTransIDParams struct {

	/* Transid.

	   The unique transaction ID for the file
	*/
	Transid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get kml for trans Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetKmlForTransIDParams) WithDefaults() *GetKmlForTransIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get kml for trans Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetKmlForTransIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get kml for trans Id params
func (o *GetKmlForTransIDParams) WithTimeout(timeout time.Duration) *GetKmlForTransIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get kml for trans Id params
func (o *GetKmlForTransIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get kml for trans Id params
func (o *GetKmlForTransIDParams) WithContext(ctx context.Context) *GetKmlForTransIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get kml for trans Id params
func (o *GetKmlForTransIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get kml for trans Id params
func (o *GetKmlForTransIDParams) WithHTTPClient(client *http.Client) *GetKmlForTransIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get kml for trans Id params
func (o *GetKmlForTransIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTransid adds the transid to the get kml for trans Id params
func (o *GetKmlForTransIDParams) WithTransid(transid string) *GetKmlForTransIDParams {
	o.SetTransid(transid)
	return o
}

// SetTransid adds the transid to the get kml for trans Id params
func (o *GetKmlForTransIDParams) SetTransid(transid string) {
	o.Transid = transid
}

// WriteToRequest writes these params to a swagger request
func (o *GetKmlForTransIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param transid
	if err := r.SetPathParam("transid", o.Transid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
