// Code generated by go-swagger; DO NOT EDIT.

package stats_group_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new stats group management API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for stats group management API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	AdminGroup(params *AdminGroupParams, opts ...ClientOption) (*AdminGroupOK, error)

	GroupMembers(params *GroupMembersParams, opts ...ClientOption) (*GroupMembersOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
AdminGroup gets group info as a stats group administrator
*/
func (a *Client) AdminGroup(params *AdminGroupParams, opts ...ClientOption) (*AdminGroupOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAdminGroupParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "adminGroup",
		Method:             "GET",
		PathPattern:        "/api/v2/group/admin",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &AdminGroupReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AdminGroupOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for adminGroup: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GroupMembers gets group members
*/
func (a *Client) GroupMembers(params *GroupMembersParams, opts ...ClientOption) (*GroupMembersOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGroupMembersParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "groupMembers",
		Method:             "GET",
		PathPattern:        "/api/v2/group/groupMembers",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GroupMembersReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GroupMembersOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for groupMembers: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
