// Code generated by go-swagger; DO NOT EDIT.

package v3_a_l_p_h_a

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewBtParams creates a new BtParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewBtParams() *BtParams {
	return &BtParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewBtParamsWithTimeout creates a new BtParams object
// with the ability to set a timeout on a request.
func NewBtParamsWithTimeout(timeout time.Duration) *BtParams {
	return &BtParams{
		timeout: timeout,
	}
}

// NewBtParamsWithContext creates a new BtParams object
// with the ability to set a context for a request.
func NewBtParamsWithContext(ctx context.Context) *BtParams {
	return &BtParams{
		Context: ctx,
	}
}

// NewBtParamsWithHTTPClient creates a new BtParams object
// with the ability to set a custom HTTPClient for a request.
func NewBtParamsWithHTTPClient(client *http.Client) *BtParams {
	return &BtParams{
		HTTPClient: client,
	}
}

/*
BtParams contains all the parameters to send to the API endpoint

	for the bt operation.

	Typically these are written to a http.Request.
*/
type BtParams struct {

	/* BtNetworkID.

	   Network ID.
	*/
	BtNetworkID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the bt params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BtParams) WithDefaults() *BtParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the bt params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BtParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the bt params
func (o *BtParams) WithTimeout(timeout time.Duration) *BtParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the bt params
func (o *BtParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the bt params
func (o *BtParams) WithContext(ctx context.Context) *BtParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the bt params
func (o *BtParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the bt params
func (o *BtParams) WithHTTPClient(client *http.Client) *BtParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the bt params
func (o *BtParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBtNetworkID adds the btNetworkID to the bt params
func (o *BtParams) WithBtNetworkID(btNetworkID string) *BtParams {
	o.SetBtNetworkID(btNetworkID)
	return o
}

// SetBtNetworkID adds the btNetworkId to the bt params
func (o *BtParams) SetBtNetworkID(btNetworkID string) {
	o.BtNetworkID = btNetworkID
}

// WriteToRequest writes these params to a swagger request
func (o *BtParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param btNetworkId
	if err := r.SetPathParam("btNetworkId", o.BtNetworkID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
