// Code generated by go-swagger; DO NOT EDIT.

package v3_a_l_p_h_a

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewWifiParams creates a new WifiParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewWifiParams() *WifiParams {
	return &WifiParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewWifiParamsWithTimeout creates a new WifiParams object
// with the ability to set a timeout on a request.
func NewWifiParamsWithTimeout(timeout time.Duration) *WifiParams {
	return &WifiParams{
		timeout: timeout,
	}
}

// NewWifiParamsWithContext creates a new WifiParams object
// with the ability to set a context for a request.
func NewWifiParamsWithContext(ctx context.Context) *WifiParams {
	return &WifiParams{
		Context: ctx,
	}
}

// NewWifiParamsWithHTTPClient creates a new WifiParams object
// with the ability to set a custom HTTPClient for a request.
func NewWifiParamsWithHTTPClient(client *http.Client) *WifiParams {
	return &WifiParams{
		HTTPClient: client,
	}
}

/*
WifiParams contains all the parameters to send to the API endpoint

	for the wifi operation.

	Typically these are written to a http.Request.
*/
type WifiParams struct {

	/* WifiNetworkID.

	   Network ID.
	*/
	WifiNetworkID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the wifi params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *WifiParams) WithDefaults() *WifiParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the wifi params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *WifiParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the wifi params
func (o *WifiParams) WithTimeout(timeout time.Duration) *WifiParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the wifi params
func (o *WifiParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the wifi params
func (o *WifiParams) WithContext(ctx context.Context) *WifiParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the wifi params
func (o *WifiParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the wifi params
func (o *WifiParams) WithHTTPClient(client *http.Client) *WifiParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the wifi params
func (o *WifiParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWifiNetworkID adds the wifiNetworkID to the wifi params
func (o *WifiParams) WithWifiNetworkID(wifiNetworkID string) *WifiParams {
	o.SetWifiNetworkID(wifiNetworkID)
	return o
}

// SetWifiNetworkID adds the wifiNetworkId to the wifi params
func (o *WifiParams) SetWifiNetworkID(wifiNetworkID string) {
	o.WifiNetworkID = wifiNetworkID
}

// WriteToRequest writes these params to a swagger request
func (o *WifiParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param wifiNetworkId
	if err := r.SetPathParam("wifiNetworkId", o.WifiNetworkID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
