// Code generated by go-swagger; DO NOT EDIT.

package bluetooth_search_and_information_tools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewSearchParams creates a new SearchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchParams() *SearchParams {
	return &SearchParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSearchParamsWithTimeout creates a new SearchParams object
// with the ability to set a timeout on a request.
func NewSearchParamsWithTimeout(timeout time.Duration) *SearchParams {
	return &SearchParams{
		timeout: timeout,
	}
}

// NewSearchParamsWithContext creates a new SearchParams object
// with the ability to set a context for a request.
func NewSearchParamsWithContext(ctx context.Context) *SearchParams {
	return &SearchParams{
		Context: ctx,
	}
}

// NewSearchParamsWithHTTPClient creates a new SearchParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchParamsWithHTTPClient(client *http.Client) *SearchParams {
	return &SearchParams{
		HTTPClient: client,
	}
}

/*
SearchParams contains all the parameters to send to the API endpoint

	for the search operation.

	Typically these are written to a http.Request.
*/
type SearchParams struct {

	/* City.

	   Street address city
	*/
	City *string

	/* ClosestLat.

	   Latitude to order by closest network (requires closestLong)
	*/
	ClosestLat *float64

	/* ClosestLong.

	   Longitude to order by closest network (requires closestLat)
	*/
	ClosestLong *float64

	/* Country.

	   Street address country
	*/
	Country *string

	/* EndTransID.

	   Latest transid by which to bound (year-level precision only), format 'yyyyMMdd-00000'
	*/
	EndTransID *string

	/* Firsttime.

	   Filter points by when they were first created (more recent than this value), condensed date/time numeric string format 'yyyyMMdd[hhmm[ss]]'
	*/
	Firsttime *string

	/* HouseNumber.

	   Street address house number
	*/
	HouseNumber *string

	/* Lasttime.

	   Filter points by how recently they've had data submitted (more recent than this value), condensed date/time numeric string format 'yyyyMMdd[hhmm[ss]]'
	*/
	Lasttime *string

	/* Lastupdt.

	   Filter points by how recently they've been updated (more recent than this value), condensed date/time numeric string format 'yyyyMMdd[hhmm[ss]]'
	*/
	Lastupdt *string

	/* Latrange1.

	   Lesser of two latitudes by which to bound the search (specify both)
	*/
	Latrange1 *float64

	/* Latrange2.

	   Greater of two latitudes by which to bound the search (specify both)
	*/
	Latrange2 *float64

	/* Longrange1.

	   Lesser of two longitudes by which to bound the search (specify both)
	*/
	Longrange1 *float64

	/* Longrange2.

	   Greater of two longitudes by which to bound the search (specify both)
	*/
	Longrange2 *float64

	/* MinQoS.

	   Minimum Quality of Signal (0-7).

	   Format: int32
	*/
	MinQoS *int32

	/* Name.

	   Include only networks exactly matching the string network name.
	*/
	Name *string

	/* Namelike.

	   Include only networks matching the string network name, allowing wildcards '%' (any string) and '_' (any character).
	*/
	Namelike *string

	/* Netid.

	   Include only networks matching the string network BSSID, e.g. '0A:2C:EF:3D:25:1B' or '0A:2C:EF'. The first three octets are required.
	*/
	Netid *string

	/* Notmine.

	   Only search for networks first seen by other users
	*/
	Notmine *string

	/* Onlymine.

	   Search only for points first discovered by the current user. Use any string to set, leave unset for general search. Can't be used with COMMAPI auth, since these are points you have locally.

	   Default: "false"
	*/
	Onlymine *string

	/* PostalCode.

	   Street address postal code
	*/
	PostalCode *string

	/* Region.

	   Street address region
	*/
	Region *string

	/* ResultsPerPage.

	   How many results to return per request. Defaults to 25 for COMMAPI, 100 for site. Bounded at 1000 for COMMAPI, 100 for site.

	   Format: int64
	*/
	ResultsPerPage *int64

	/* Road.

	   Street address road
	*/
	Road *string

	/* SearchAfter.

	   Put in the previous page's searchAfter result to get the next page. Use this instead of 'first'
	*/
	SearchAfter *string

	/* ShowBle.

	   Include BLE networks

	   Default: "true"
	*/
	ShowBle *string

	/* ShowBt.

	   Include BT networks

	   Default: "true"
	*/
	ShowBt *string

	/* StartTransID.

	   Earliest transid by which to bound (year-level precision only), format 'yyyyMMdd-00000'
	*/
	StartTransID *string

	/* Variance.

	   How tightly to bound queries against the provided latitude/longitude box. Value must be between 0.001 and 0.2. Intended for use with non-exact decimals and geocoded bounds.
	*/
	Variance *float64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchParams) WithDefaults() *SearchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchParams) SetDefaults() {
	var (
		onlymineDefault = string("false")

		showBleDefault = string("true")

		showBtDefault = string("true")
	)

	val := SearchParams{
		Onlymine: &onlymineDefault,
		ShowBle:  &showBleDefault,
		ShowBt:   &showBtDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the search params
func (o *SearchParams) WithTimeout(timeout time.Duration) *SearchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search params
func (o *SearchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search params
func (o *SearchParams) WithContext(ctx context.Context) *SearchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search params
func (o *SearchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search params
func (o *SearchParams) WithHTTPClient(client *http.Client) *SearchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search params
func (o *SearchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCity adds the city to the search params
func (o *SearchParams) WithCity(city *string) *SearchParams {
	o.SetCity(city)
	return o
}

// SetCity adds the city to the search params
func (o *SearchParams) SetCity(city *string) {
	o.City = city
}

// WithClosestLat adds the closestLat to the search params
func (o *SearchParams) WithClosestLat(closestLat *float64) *SearchParams {
	o.SetClosestLat(closestLat)
	return o
}

// SetClosestLat adds the closestLat to the search params
func (o *SearchParams) SetClosestLat(closestLat *float64) {
	o.ClosestLat = closestLat
}

// WithClosestLong adds the closestLong to the search params
func (o *SearchParams) WithClosestLong(closestLong *float64) *SearchParams {
	o.SetClosestLong(closestLong)
	return o
}

// SetClosestLong adds the closestLong to the search params
func (o *SearchParams) SetClosestLong(closestLong *float64) {
	o.ClosestLong = closestLong
}

// WithCountry adds the country to the search params
func (o *SearchParams) WithCountry(country *string) *SearchParams {
	o.SetCountry(country)
	return o
}

// SetCountry adds the country to the search params
func (o *SearchParams) SetCountry(country *string) {
	o.Country = country
}

// WithEndTransID adds the endTransID to the search params
func (o *SearchParams) WithEndTransID(endTransID *string) *SearchParams {
	o.SetEndTransID(endTransID)
	return o
}

// SetEndTransID adds the endTransId to the search params
func (o *SearchParams) SetEndTransID(endTransID *string) {
	o.EndTransID = endTransID
}

// WithFirsttime adds the firsttime to the search params
func (o *SearchParams) WithFirsttime(firsttime *string) *SearchParams {
	o.SetFirsttime(firsttime)
	return o
}

// SetFirsttime adds the firsttime to the search params
func (o *SearchParams) SetFirsttime(firsttime *string) {
	o.Firsttime = firsttime
}

// WithHouseNumber adds the houseNumber to the search params
func (o *SearchParams) WithHouseNumber(houseNumber *string) *SearchParams {
	o.SetHouseNumber(houseNumber)
	return o
}

// SetHouseNumber adds the houseNumber to the search params
func (o *SearchParams) SetHouseNumber(houseNumber *string) {
	o.HouseNumber = houseNumber
}

// WithLasttime adds the lasttime to the search params
func (o *SearchParams) WithLasttime(lasttime *string) *SearchParams {
	o.SetLasttime(lasttime)
	return o
}

// SetLasttime adds the lasttime to the search params
func (o *SearchParams) SetLasttime(lasttime *string) {
	o.Lasttime = lasttime
}

// WithLastupdt adds the lastupdt to the search params
func (o *SearchParams) WithLastupdt(lastupdt *string) *SearchParams {
	o.SetLastupdt(lastupdt)
	return o
}

// SetLastupdt adds the lastupdt to the search params
func (o *SearchParams) SetLastupdt(lastupdt *string) {
	o.Lastupdt = lastupdt
}

// WithLatrange1 adds the latrange1 to the search params
func (o *SearchParams) WithLatrange1(latrange1 *float64) *SearchParams {
	o.SetLatrange1(latrange1)
	return o
}

// SetLatrange1 adds the latrange1 to the search params
func (o *SearchParams) SetLatrange1(latrange1 *float64) {
	o.Latrange1 = latrange1
}

// WithLatrange2 adds the latrange2 to the search params
func (o *SearchParams) WithLatrange2(latrange2 *float64) *SearchParams {
	o.SetLatrange2(latrange2)
	return o
}

// SetLatrange2 adds the latrange2 to the search params
func (o *SearchParams) SetLatrange2(latrange2 *float64) {
	o.Latrange2 = latrange2
}

// WithLongrange1 adds the longrange1 to the search params
func (o *SearchParams) WithLongrange1(longrange1 *float64) *SearchParams {
	o.SetLongrange1(longrange1)
	return o
}

// SetLongrange1 adds the longrange1 to the search params
func (o *SearchParams) SetLongrange1(longrange1 *float64) {
	o.Longrange1 = longrange1
}

// WithLongrange2 adds the longrange2 to the search params
func (o *SearchParams) WithLongrange2(longrange2 *float64) *SearchParams {
	o.SetLongrange2(longrange2)
	return o
}

// SetLongrange2 adds the longrange2 to the search params
func (o *SearchParams) SetLongrange2(longrange2 *float64) {
	o.Longrange2 = longrange2
}

// WithMinQoS adds the minQoS to the search params
func (o *SearchParams) WithMinQoS(minQoS *int32) *SearchParams {
	o.SetMinQoS(minQoS)
	return o
}

// SetMinQoS adds the minQoS to the search params
func (o *SearchParams) SetMinQoS(minQoS *int32) {
	o.MinQoS = minQoS
}

// WithName adds the name to the search params
func (o *SearchParams) WithName(name *string) *SearchParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the search params
func (o *SearchParams) SetName(name *string) {
	o.Name = name
}

// WithNamelike adds the namelike to the search params
func (o *SearchParams) WithNamelike(namelike *string) *SearchParams {
	o.SetNamelike(namelike)
	return o
}

// SetNamelike adds the namelike to the search params
func (o *SearchParams) SetNamelike(namelike *string) {
	o.Namelike = namelike
}

// WithNetid adds the netid to the search params
func (o *SearchParams) WithNetid(netid *string) *SearchParams {
	o.SetNetid(netid)
	return o
}

// SetNetid adds the netid to the search params
func (o *SearchParams) SetNetid(netid *string) {
	o.Netid = netid
}

// WithNotmine adds the notmine to the search params
func (o *SearchParams) WithNotmine(notmine *string) *SearchParams {
	o.SetNotmine(notmine)
	return o
}

// SetNotmine adds the notmine to the search params
func (o *SearchParams) SetNotmine(notmine *string) {
	o.Notmine = notmine
}

// WithOnlymine adds the onlymine to the search params
func (o *SearchParams) WithOnlymine(onlymine *string) *SearchParams {
	o.SetOnlymine(onlymine)
	return o
}

// SetOnlymine adds the onlymine to the search params
func (o *SearchParams) SetOnlymine(onlymine *string) {
	o.Onlymine = onlymine
}

// WithPostalCode adds the postalCode to the search params
func (o *SearchParams) WithPostalCode(postalCode *string) *SearchParams {
	o.SetPostalCode(postalCode)
	return o
}

// SetPostalCode adds the postalCode to the search params
func (o *SearchParams) SetPostalCode(postalCode *string) {
	o.PostalCode = postalCode
}

// WithRegion adds the region to the search params
func (o *SearchParams) WithRegion(region *string) *SearchParams {
	o.SetRegion(region)
	return o
}

// SetRegion adds the region to the search params
func (o *SearchParams) SetRegion(region *string) {
	o.Region = region
}

// WithResultsPerPage adds the resultsPerPage to the search params
func (o *SearchParams) WithResultsPerPage(resultsPerPage *int64) *SearchParams {
	o.SetResultsPerPage(resultsPerPage)
	return o
}

// SetResultsPerPage adds the resultsPerPage to the search params
func (o *SearchParams) SetResultsPerPage(resultsPerPage *int64) {
	o.ResultsPerPage = resultsPerPage
}

// WithRoad adds the road to the search params
func (o *SearchParams) WithRoad(road *string) *SearchParams {
	o.SetRoad(road)
	return o
}

// SetRoad adds the road to the search params
func (o *SearchParams) SetRoad(road *string) {
	o.Road = road
}

// WithSearchAfter adds the searchAfter to the search params
func (o *SearchParams) WithSearchAfter(searchAfter *string) *SearchParams {
	o.SetSearchAfter(searchAfter)
	return o
}

// SetSearchAfter adds the searchAfter to the search params
func (o *SearchParams) SetSearchAfter(searchAfter *string) {
	o.SearchAfter = searchAfter
}

// WithShowBle adds the showBle to the search params
func (o *SearchParams) WithShowBle(showBle *string) *SearchParams {
	o.SetShowBle(showBle)
	return o
}

// SetShowBle adds the showBle to the search params
func (o *SearchParams) SetShowBle(showBle *string) {
	o.ShowBle = showBle
}

// WithShowBt adds the showBt to the search params
func (o *SearchParams) WithShowBt(showBt *string) *SearchParams {
	o.SetShowBt(showBt)
	return o
}

// SetShowBt adds the showBt to the search params
func (o *SearchParams) SetShowBt(showBt *string) {
	o.ShowBt = showBt
}

// WithStartTransID adds the startTransID to the search params
func (o *SearchParams) WithStartTransID(startTransID *string) *SearchParams {
	o.SetStartTransID(startTransID)
	return o
}

// SetStartTransID adds the startTransId to the search params
func (o *SearchParams) SetStartTransID(startTransID *string) {
	o.StartTransID = startTransID
}

// WithVariance adds the variance to the search params
func (o *SearchParams) WithVariance(variance *float64) *SearchParams {
	o.SetVariance(variance)
	return o
}

// SetVariance adds the variance to the search params
func (o *SearchParams) SetVariance(variance *float64) {
	o.Variance = variance
}

// WriteToRequest writes these params to a swagger request
func (o *SearchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.City != nil {

		// query param city
		var qrCity string

		if o.City != nil {
			qrCity = *o.City
		}
		qCity := qrCity
		if qCity != "" {

			if err := r.SetQueryParam("city", qCity); err != nil {
				return err
			}
		}
	}

	if o.ClosestLat != nil {

		// query param closestLat
		var qrClosestLat float64

		if o.ClosestLat != nil {
			qrClosestLat = *o.ClosestLat
		}
		qClosestLat := swag.FormatFloat64(qrClosestLat)
		if qClosestLat != "" {

			if err := r.SetQueryParam("closestLat", qClosestLat); err != nil {
				return err
			}
		}
	}

	if o.ClosestLong != nil {

		// query param closestLong
		var qrClosestLong float64

		if o.ClosestLong != nil {
			qrClosestLong = *o.ClosestLong
		}
		qClosestLong := swag.FormatFloat64(qrClosestLong)
		if qClosestLong != "" {

			if err := r.SetQueryParam("closestLong", qClosestLong); err != nil {
				return err
			}
		}
	}

	if o.Country != nil {

		// query param country
		var qrCountry string

		if o.Country != nil {
			qrCountry = *o.Country
		}
		qCountry := qrCountry
		if qCountry != "" {

			if err := r.SetQueryParam("country", qCountry); err != nil {
				return err
			}
		}
	}

	if o.EndTransID != nil {

		// query param endTransID
		var qrEndTransID string

		if o.EndTransID != nil {
			qrEndTransID = *o.EndTransID
		}
		qEndTransID := qrEndTransID
		if qEndTransID != "" {

			if err := r.SetQueryParam("endTransID", qEndTransID); err != nil {
				return err
			}
		}
	}

	if o.Firsttime != nil {

		// query param firsttime
		var qrFirsttime string

		if o.Firsttime != nil {
			qrFirsttime = *o.Firsttime
		}
		qFirsttime := qrFirsttime
		if qFirsttime != "" {

			if err := r.SetQueryParam("firsttime", qFirsttime); err != nil {
				return err
			}
		}
	}

	if o.HouseNumber != nil {

		// query param houseNumber
		var qrHouseNumber string

		if o.HouseNumber != nil {
			qrHouseNumber = *o.HouseNumber
		}
		qHouseNumber := qrHouseNumber
		if qHouseNumber != "" {

			if err := r.SetQueryParam("houseNumber", qHouseNumber); err != nil {
				return err
			}
		}
	}

	if o.Lasttime != nil {

		// query param lasttime
		var qrLasttime string

		if o.Lasttime != nil {
			qrLasttime = *o.Lasttime
		}
		qLasttime := qrLasttime
		if qLasttime != "" {

			if err := r.SetQueryParam("lasttime", qLasttime); err != nil {
				return err
			}
		}
	}

	if o.Lastupdt != nil {

		// query param lastupdt
		var qrLastupdt string

		if o.Lastupdt != nil {
			qrLastupdt = *o.Lastupdt
		}
		qLastupdt := qrLastupdt
		if qLastupdt != "" {

			if err := r.SetQueryParam("lastupdt", qLastupdt); err != nil {
				return err
			}
		}
	}

	if o.Latrange1 != nil {

		// query param latrange1
		var qrLatrange1 float64

		if o.Latrange1 != nil {
			qrLatrange1 = *o.Latrange1
		}
		qLatrange1 := swag.FormatFloat64(qrLatrange1)
		if qLatrange1 != "" {

			if err := r.SetQueryParam("latrange1", qLatrange1); err != nil {
				return err
			}
		}
	}

	if o.Latrange2 != nil {

		// query param latrange2
		var qrLatrange2 float64

		if o.Latrange2 != nil {
			qrLatrange2 = *o.Latrange2
		}
		qLatrange2 := swag.FormatFloat64(qrLatrange2)
		if qLatrange2 != "" {

			if err := r.SetQueryParam("latrange2", qLatrange2); err != nil {
				return err
			}
		}
	}

	if o.Longrange1 != nil {

		// query param longrange1
		var qrLongrange1 float64

		if o.Longrange1 != nil {
			qrLongrange1 = *o.Longrange1
		}
		qLongrange1 := swag.FormatFloat64(qrLongrange1)
		if qLongrange1 != "" {

			if err := r.SetQueryParam("longrange1", qLongrange1); err != nil {
				return err
			}
		}
	}

	if o.Longrange2 != nil {

		// query param longrange2
		var qrLongrange2 float64

		if o.Longrange2 != nil {
			qrLongrange2 = *o.Longrange2
		}
		qLongrange2 := swag.FormatFloat64(qrLongrange2)
		if qLongrange2 != "" {

			if err := r.SetQueryParam("longrange2", qLongrange2); err != nil {
				return err
			}
		}
	}

	if o.MinQoS != nil {

		// query param minQoS
		var qrMinQoS int32

		if o.MinQoS != nil {
			qrMinQoS = *o.MinQoS
		}
		qMinQoS := swag.FormatInt32(qrMinQoS)
		if qMinQoS != "" {

			if err := r.SetQueryParam("minQoS", qMinQoS); err != nil {
				return err
			}
		}
	}

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if o.Namelike != nil {

		// query param namelike
		var qrNamelike string

		if o.Namelike != nil {
			qrNamelike = *o.Namelike
		}
		qNamelike := qrNamelike
		if qNamelike != "" {

			if err := r.SetQueryParam("namelike", qNamelike); err != nil {
				return err
			}
		}
	}

	if o.Netid != nil {

		// query param netid
		var qrNetid string

		if o.Netid != nil {
			qrNetid = *o.Netid
		}
		qNetid := qrNetid
		if qNetid != "" {

			if err := r.SetQueryParam("netid", qNetid); err != nil {
				return err
			}
		}
	}

	if o.Notmine != nil {

		// query param notmine
		var qrNotmine string

		if o.Notmine != nil {
			qrNotmine = *o.Notmine
		}
		qNotmine := qrNotmine
		if qNotmine != "" {

			if err := r.SetQueryParam("notmine", qNotmine); err != nil {
				return err
			}
		}
	}

	if o.Onlymine != nil {

		// query param onlymine
		var qrOnlymine string

		if o.Onlymine != nil {
			qrOnlymine = *o.Onlymine
		}
		qOnlymine := qrOnlymine
		if qOnlymine != "" {

			if err := r.SetQueryParam("onlymine", qOnlymine); err != nil {
				return err
			}
		}
	}

	if o.PostalCode != nil {

		// query param postalCode
		var qrPostalCode string

		if o.PostalCode != nil {
			qrPostalCode = *o.PostalCode
		}
		qPostalCode := qrPostalCode
		if qPostalCode != "" {

			if err := r.SetQueryParam("postalCode", qPostalCode); err != nil {
				return err
			}
		}
	}

	if o.Region != nil {

		// query param region
		var qrRegion string

		if o.Region != nil {
			qrRegion = *o.Region
		}
		qRegion := qrRegion
		if qRegion != "" {

			if err := r.SetQueryParam("region", qRegion); err != nil {
				return err
			}
		}
	}

	if o.ResultsPerPage != nil {

		// query param resultsPerPage
		var qrResultsPerPage int64

		if o.ResultsPerPage != nil {
			qrResultsPerPage = *o.ResultsPerPage
		}
		qResultsPerPage := swag.FormatInt64(qrResultsPerPage)
		if qResultsPerPage != "" {

			if err := r.SetQueryParam("resultsPerPage", qResultsPerPage); err != nil {
				return err
			}
		}
	}

	if o.Road != nil {

		// query param road
		var qrRoad string

		if o.Road != nil {
			qrRoad = *o.Road
		}
		qRoad := qrRoad
		if qRoad != "" {

			if err := r.SetQueryParam("road", qRoad); err != nil {
				return err
			}
		}
	}

	if o.SearchAfter != nil {

		// query param searchAfter
		var qrSearchAfter string

		if o.SearchAfter != nil {
			qrSearchAfter = *o.SearchAfter
		}
		qSearchAfter := qrSearchAfter
		if qSearchAfter != "" {

			if err := r.SetQueryParam("searchAfter", qSearchAfter); err != nil {
				return err
			}
		}
	}

	if o.ShowBle != nil {

		// query param showBle
		var qrShowBle string

		if o.ShowBle != nil {
			qrShowBle = *o.ShowBle
		}
		qShowBle := qrShowBle
		if qShowBle != "" {

			if err := r.SetQueryParam("showBle", qShowBle); err != nil {
				return err
			}
		}
	}

	if o.ShowBt != nil {

		// query param showBt
		var qrShowBt string

		if o.ShowBt != nil {
			qrShowBt = *o.ShowBt
		}
		qShowBt := qrShowBt
		if qShowBt != "" {

			if err := r.SetQueryParam("showBt", qShowBt); err != nil {
				return err
			}
		}
	}

	if o.StartTransID != nil {

		// query param startTransID
		var qrStartTransID string

		if o.StartTransID != nil {
			qrStartTransID = *o.StartTransID
		}
		qStartTransID := qrStartTransID
		if qStartTransID != "" {

			if err := r.SetQueryParam("startTransID", qStartTransID); err != nil {
				return err
			}
		}
	}

	if o.Variance != nil {

		// query param variance
		var qrVariance float64

		if o.Variance != nil {
			qrVariance = *o.Variance
		}
		qVariance := swag.FormatFloat64(qrVariance)
		if qVariance != "" {

			if err := r.SetQueryParam("variance", qVariance); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
