// Code generated by go-swagger; DO NOT EDIT.

package wigle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/borud/wigle/wigle/bluetooth_search_and_information_tools"
	"github.com/borud/wigle/wigle/cell_search_and_information_tools"
	"github.com/borud/wigle/wigle/network_observation_file_upload_and_status"
	"github.com/borud/wigle/wigle/network_search_and_information_tools"
	"github.com/borud/wigle/wigle/statistics_and_information"
	"github.com/borud/wigle/wigle/stats_group_management"
	"github.com/borud/wigle/wigle/user_profile_operations"
	"github.com/borud/wigle/wigle/v3_a_l_p_h_a"
)

// Default wigle HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new wigle HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Wigle {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new wigle HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Wigle {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new wigle client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Wigle {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Wigle)
	cli.Transport = transport
	cli.BluetoothSearchAndInformationTools = bluetooth_search_and_information_tools.New(transport, formats)
	cli.CellSearchAndInformationTools = cell_search_and_information_tools.New(transport, formats)
	cli.NetworkObservationFileUploadAndStatus = network_observation_file_upload_and_status.New(transport, formats)
	cli.NetworkSearchAndInformationTools = network_search_and_information_tools.New(transport, formats)
	cli.StatisticsAndInformation = statistics_and_information.New(transport, formats)
	cli.StatsGroupManagement = stats_group_management.New(transport, formats)
	cli.UserProfileOperations = user_profile_operations.New(transport, formats)
	cli.V3alpha = v3_a_l_p_h_a.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Wigle is a client for wigle
type Wigle struct {
	BluetoothSearchAndInformationTools bluetooth_search_and_information_tools.ClientService

	CellSearchAndInformationTools cell_search_and_information_tools.ClientService

	NetworkObservationFileUploadAndStatus network_observation_file_upload_and_status.ClientService

	NetworkSearchAndInformationTools network_search_and_information_tools.ClientService

	StatisticsAndInformation statistics_and_information.ClientService

	StatsGroupManagement stats_group_management.ClientService

	UserProfileOperations user_profile_operations.ClientService

	V3alpha v3_a_l_p_h_a.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Wigle) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.BluetoothSearchAndInformationTools.SetTransport(transport)
	c.CellSearchAndInformationTools.SetTransport(transport)
	c.NetworkObservationFileUploadAndStatus.SetTransport(transport)
	c.NetworkSearchAndInformationTools.SetTransport(transport)
	c.StatisticsAndInformation.SetTransport(transport)
	c.StatsGroupManagement.SetTransport(transport)
	c.UserProfileOperations.SetTransport(transport)
	c.V3alpha.SetTransport(transport)
}
