// Code generated by go-swagger; DO NOT EDIT.

package network_search_and_information_tools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGeocodeParams creates a new GeocodeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGeocodeParams() *GeocodeParams {
	return &GeocodeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGeocodeParamsWithTimeout creates a new GeocodeParams object
// with the ability to set a timeout on a request.
func NewGeocodeParamsWithTimeout(timeout time.Duration) *GeocodeParams {
	return &GeocodeParams{
		timeout: timeout,
	}
}

// NewGeocodeParamsWithContext creates a new GeocodeParams object
// with the ability to set a context for a request.
func NewGeocodeParamsWithContext(ctx context.Context) *GeocodeParams {
	return &GeocodeParams{
		Context: ctx,
	}
}

// NewGeocodeParamsWithHTTPClient creates a new GeocodeParams object
// with the ability to set a custom HTTPClient for a request.
func NewGeocodeParamsWithHTTPClient(client *http.Client) *GeocodeParams {
	return &GeocodeParams{
		HTTPClient: client,
	}
}

/*
GeocodeParams contains all the parameters to send to the API endpoint

	for the geocode operation.

	Typically these are written to a http.Request.
*/
type GeocodeParams struct {

	/* Addresscode.

	   An address string, Street, City, State/Region, Country
	*/
	Addresscode *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the geocode params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GeocodeParams) WithDefaults() *GeocodeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the geocode params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GeocodeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the geocode params
func (o *GeocodeParams) WithTimeout(timeout time.Duration) *GeocodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the geocode params
func (o *GeocodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the geocode params
func (o *GeocodeParams) WithContext(ctx context.Context) *GeocodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the geocode params
func (o *GeocodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the geocode params
func (o *GeocodeParams) WithHTTPClient(client *http.Client) *GeocodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the geocode params
func (o *GeocodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddresscode adds the addresscode to the geocode params
func (o *GeocodeParams) WithAddresscode(addresscode *string) *GeocodeParams {
	o.SetAddresscode(addresscode)
	return o
}

// SetAddresscode adds the addresscode to the geocode params
func (o *GeocodeParams) SetAddresscode(addresscode *string) {
	o.Addresscode = addresscode
}

// WriteToRequest writes these params to a swagger request
func (o *GeocodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Addresscode != nil {

		// query param addresscode
		var qrAddresscode string

		if o.Addresscode != nil {
			qrAddresscode = *o.Addresscode
		}
		qAddresscode := qrAddresscode
		if qAddresscode != "" {

			if err := r.SetQueryParam("addresscode", qAddresscode); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
