// Code generated by go-swagger; DO NOT EDIT.

package user_profile_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/borud/wigle/models"
)

// APITokenReader is a Reader for the APIToken structure.
type APITokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *APITokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAPITokenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewAPITokenNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAPITokenOK creates a APITokenOK with default headers values
func NewAPITokenOK() *APITokenOK {
	return &APITokenOK{}
}

/*
APITokenOK describes a response with status code 200, with default header values.

Request succeeded
*/
type APITokenOK struct {
	Payload *models.ResettableAuthTokenResponse
}

// IsSuccess returns true when this api token o k response has a 2xx status code
func (o *APITokenOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this api token o k response has a 3xx status code
func (o *APITokenOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this api token o k response has a 4xx status code
func (o *APITokenOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this api token o k response has a 5xx status code
func (o *APITokenOK) IsServerError() bool {
	return false
}

// IsCode returns true when this api token o k response a status code equal to that given
func (o *APITokenOK) IsCode(code int) bool {
	return code == 200
}

func (o *APITokenOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/profile/apiToken][%d] apiTokenOK  %+v", 200, o.Payload)
}

func (o *APITokenOK) String() string {
	return fmt.Sprintf("[GET /api/v2/profile/apiToken][%d] apiTokenOK  %+v", 200, o.Payload)
}

func (o *APITokenOK) GetPayload() *models.ResettableAuthTokenResponse {
	return o.Payload
}

func (o *APITokenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResettableAuthTokenResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAPITokenNoContent creates a APITokenNoContent with default headers values
func NewAPITokenNoContent() *APITokenNoContent {
	return &APITokenNoContent{}
}

/*
APITokenNoContent describes a response with status code 204, with default header values.

Request successful, but no tokens present for user
*/
type APITokenNoContent struct {
}

// IsSuccess returns true when this api token no content response has a 2xx status code
func (o *APITokenNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this api token no content response has a 3xx status code
func (o *APITokenNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this api token no content response has a 4xx status code
func (o *APITokenNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this api token no content response has a 5xx status code
func (o *APITokenNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this api token no content response a status code equal to that given
func (o *APITokenNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *APITokenNoContent) Error() string {
	return fmt.Sprintf("[GET /api/v2/profile/apiToken][%d] apiTokenNoContent ", 204)
}

func (o *APITokenNoContent) String() string {
	return fmt.Sprintf("[GET /api/v2/profile/apiToken][%d] apiTokenNoContent ", 204)
}

func (o *APITokenNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
