// Code generated by go-swagger; DO NOT EDIT.

package user_profile_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAPITokenParams creates a new APITokenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAPITokenParams() *APITokenParams {
	return &APITokenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAPITokenParamsWithTimeout creates a new APITokenParams object
// with the ability to set a timeout on a request.
func NewAPITokenParamsWithTimeout(timeout time.Duration) *APITokenParams {
	return &APITokenParams{
		timeout: timeout,
	}
}

// NewAPITokenParamsWithContext creates a new APITokenParams object
// with the ability to set a context for a request.
func NewAPITokenParamsWithContext(ctx context.Context) *APITokenParams {
	return &APITokenParams{
		Context: ctx,
	}
}

// NewAPITokenParamsWithHTTPClient creates a new APITokenParams object
// with the ability to set a custom HTTPClient for a request.
func NewAPITokenParamsWithHTTPClient(client *http.Client) *APITokenParams {
	return &APITokenParams{
		HTTPClient: client,
	}
}

/*
APITokenParams contains all the parameters to send to the API endpoint

	for the api token operation.

	Typically these are written to a http.Request.
*/
type APITokenParams struct {

	/* Type.

	   Token types - 'API', 'COMMAPI', or 'ANDROID'
	*/
	Type *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the api token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *APITokenParams) WithDefaults() *APITokenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the api token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *APITokenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the api token params
func (o *APITokenParams) WithTimeout(timeout time.Duration) *APITokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the api token params
func (o *APITokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the api token params
func (o *APITokenParams) WithContext(ctx context.Context) *APITokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the api token params
func (o *APITokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the api token params
func (o *APITokenParams) WithHTTPClient(client *http.Client) *APITokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the api token params
func (o *APITokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithType adds the typeVar to the api token params
func (o *APITokenParams) WithType(typeVar *string) *APITokenParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the api token params
func (o *APITokenParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *APITokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Type != nil {

		// query param type
		var qrType string

		if o.Type != nil {
			qrType = *o.Type
		}
		qType := qrType
		if qType != "" {

			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
