// Code generated by go-swagger; DO NOT EDIT.

package user_profile_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new user profile operations API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for user profile operations API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	APIToken(params *APITokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*APITokenOK, *APITokenNoContent, error)

	User(params *UserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UserOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
APIToken gets all authorization tokens for the logged in user
*/
func (a *Client) APIToken(params *APITokenParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*APITokenOK, *APITokenNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAPITokenParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "apiToken",
		Method:             "GET",
		PathPattern:        "/api/v2/profile/apiToken",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &APITokenReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, nil, err
	}
	switch value := result.(type) {
	case *APITokenOK:
		return value, nil, nil
	case *APITokenNoContent:
		return nil, value, nil
	}
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for user_profile_operations: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
User gets the user object for the current logged in user

See basic user information.
*/
func (a *Client) User(params *UserParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UserOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUserParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "user",
		Method:             "GET",
		PathPattern:        "/api/v2/profile/user",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UserReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UserOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for user: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
