// Code generated by go-swagger; DO NOT EDIT.

package user_profile_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUserParams creates a new UserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUserParams() *UserParams {
	return &UserParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUserParamsWithTimeout creates a new UserParams object
// with the ability to set a timeout on a request.
func NewUserParamsWithTimeout(timeout time.Duration) *UserParams {
	return &UserParams{
		timeout: timeout,
	}
}

// NewUserParamsWithContext creates a new UserParams object
// with the ability to set a context for a request.
func NewUserParamsWithContext(ctx context.Context) *UserParams {
	return &UserParams{
		Context: ctx,
	}
}

// NewUserParamsWithHTTPClient creates a new UserParams object
// with the ability to set a custom HTTPClient for a request.
func NewUserParamsWithHTTPClient(client *http.Client) *UserParams {
	return &UserParams{
		HTTPClient: client,
	}
}

/*
UserParams contains all the parameters to send to the API endpoint

	for the user operation.

	Typically these are written to a http.Request.
*/
type UserParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UserParams) WithDefaults() *UserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the user params
func (o *UserParams) WithTimeout(timeout time.Duration) *UserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the user params
func (o *UserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the user params
func (o *UserParams) WithContext(ctx context.Context) *UserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the user params
func (o *UserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the user params
func (o *UserParams) WithHTTPClient(client *http.Client) *UserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the user params
func (o *UserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *UserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
