// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EncryptionStat encryption stat
//
// swagger:model EncryptionStat
type EncryptionStat struct {

	// count
	Count int64 `json:"count,omitempty"`

	// wep
	Wep string `json:"wep,omitempty"`
}

// Validate validates this encryption stat
func (m *EncryptionStat) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this encryption stat based on context it is used
func (m *EncryptionStat) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EncryptionStat) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EncryptionStat) UnmarshalBinary(b []byte) error {
	var res EncryptionStat
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
