// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GroupStat group stat
//
// swagger:model GroupStat
type GroupStat struct {

	// discovered
	Discovered int64 `json:"discovered,omitempty"`

	// gen disc
	GenDisc int64 `json:"genDisc,omitempty"`

	// group Id
	GroupID string `json:"groupId,omitempty"`

	// group name
	GroupName string `json:"groupName,omitempty"`

	// group owner
	GroupOwner bool `json:"groupOwner,omitempty"`

	// joined
	Joined bool `json:"joined,omitempty"`

	// members
	Members int64 `json:"members,omitempty"`

	// owner
	Owner string `json:"owner,omitempty"`

	// total
	Total int64 `json:"total,omitempty"`
}

// Validate validates this group stat
func (m *GroupStat) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this group stat based on context it is used
func (m *GroupStat) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GroupStat) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GroupStat) UnmarshalBinary(b []byte) error {
	var res GroupStat
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
