// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Group group
//
// swagger:model Group
type Group struct {

	// auth type
	AuthType string `json:"authType,omitempty"`

	// discovered
	Discovered int64 `json:"discovered,omitempty"`

	// gen disc
	GenDisc int64 `json:"genDisc,omitempty"`

	// group Id
	GroupID string `json:"groupId,omitempty"`

	// group name
	GroupName string `json:"groupName,omitempty"`

	// group owner
	GroupOwner bool `json:"groupOwner,omitempty"`

	// owner
	Owner string `json:"owner,omitempty"`

	// total
	Total int64 `json:"total,omitempty"`
}

// Validate validates this group
func (m *Group) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this group based on context it is used
func (m *Group) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Group) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Group) UnmarshalBinary(b []byte) error {
	var res Group
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
