// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NetCommentResponse net comment response
//
// swagger:model NetCommentResponse
type NetCommentResponse struct {

	// comment
	Comment string `json:"comment,omitempty"`

	// netid
	Netid string `json:"netid,omitempty"`

	// success
	Success bool `json:"success,omitempty"`
}

// Validate validates this net comment response
func (m *NetCommentResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this net comment response based on context it is used
func (m *NetCommentResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NetCommentResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NetCommentResponse) UnmarshalBinary(b []byte) error {
	var res NetCommentResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
