// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostalStat postal stat
//
// swagger:model PostalStat
type PostalStat struct {

	// bt count
	BtCount int64 `json:"btCount,omitempty"`

	// cell count
	CellCount int64 `json:"cellCount,omitempty"`

	// postal code
	PostalCode string `json:"postalCode,omitempty"`

	// wifi count
	WifiCount int64 `json:"wifiCount,omitempty"`
}

// Validate validates this postal stat
func (m *PostalStat) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this postal stat based on context it is used
func (m *PostalStat) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostalStat) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostalStat) UnmarshalBinary(b []byte) error {
	var res PostalStat
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
