// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StreetAddress street address
//
// swagger:model StreetAddress
type StreetAddress struct {

	// city
	City string `json:"city,omitempty"`

	// country
	Country string `json:"country,omitempty"`

	// housenumber
	Housenumber string `json:"housenumber,omitempty"`

	// postalcode
	Postalcode string `json:"postalcode,omitempty"`

	// region
	Region string `json:"region,omitempty"`

	// road
	Road string `json:"road,omitempty"`
}

// Validate validates this street address
func (m *StreetAddress) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this street address based on context it is used
func (m *StreetAddress) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StreetAddress) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StreetAddress) UnmarshalBinary(b []byte) error {
	var res StreetAddress
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
