// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TransidResponse transid response
//
// swagger:model TransidResponse
type TransidResponse struct {

	// file
	File string `json:"file,omitempty"`

	// size
	Size int64 `json:"size,omitempty"`

	// trans Id
	TransID string `json:"transId,omitempty"`
}

// Validate validates this transid response
func (m *TransidResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this transid response based on context it is used
func (m *TransidResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TransidResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TransidResponse) UnmarshalBinary(b []byte) error {
	var res TransidResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
